// <auto-generated />
using System;
using API.DataAccess.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.DataAccess.SQL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220904214359_InitTwo")]
    partial class InitTwo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("API.Core.Models.Product", b =>
                {
                    b.Property<string>("mID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("mDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("mIsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("mTimeEntered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("mTimeModified")
                        .HasColumnType("datetime2");

                    b.Property<double>("mUnitPrice")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
